[package]
name = "new_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfn_candid ="0.7.0"
dfn_protobuf = "0.7.0"
dfn_types = "0.7.0"
dfn_candid_derive = "0.7.0"
dfn_macros = "0.7.0"
